# Para o Jogo "Tetris", Problema 02, no DE1-SoC

all:
	gcc -o tetris ADXL345.c GPIO.c jogabilidade.c tetris.c vga.s -std=c99
	sudo ./tetris

	# gcc -o vga_test ADXL345.c GPIO.c jogabilidade.c vga.s vga_test.c -std=c99
	# sudo ./vga_test
